=== karolinee/University/Programowanie pod Windows .NET/lista9/2.4/students_list.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:Validator="http://www.w3.org/2001/XMLSchema-instance" attributeFormDefault="unqualified" elementFormDefault="qualified" targetNamespace="StudentsData" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="Students">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" name="Student">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Name" type="xs:string" />
              <xs:element name="Surname" type="xs:string" />
              <xs:element name="Date_of_birth" type="xs:date" />
              <xs:element name="Adress_pernam">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="City" type="xs:string" />
                    <xs:element minOccurs="0" name="Street" type="xs:string" />
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="Adress_temp">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="City" type="xs:string" />
                    <xs:element minOccurs="0" name="Street" type="xs:string" />
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="Classes">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element maxOccurs="unbounded" name="Class">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="Name" type="xs:string" />
                          <xs:element name="Grade" type="xs:unsignedByte" />
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== karolinee/University/Programowanie pod Windows .NET/lista9/2.4/students_list.xml
<?xml version="1.0"?>
<Students xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xsi:schemaLocation="StudentsData students_list.xsd" xmlns="StudentsData">
  <Student>
    <Name>Anna</Name>
    <Surname>Kowalska</Surname>
    <Date_of_birth>1999-09-09</Date_of_birth>
    <Adress_pernam>
      <City>Wrocław</City>
      <Street>Podwale</Street>
    </Adress_pernam>
    <Adress_temp>
      <City>Warszawa</City>
    </Adress_temp>
    <Classes>
      <Class>
        <Name>Algorytmy</Name>
        <Grade>5</Grade>
      </Class>
      <Class>
        <Name>Bazy</Name>
        <Grade>4</Grade>
      </Class>
    </Classes>
  </Student>
  <Student>
    <Name>Bartosz</Name>
    <Surname>Nowak</Surname>
    <Date_of_birth>1999-08-08</Date_of_birth>
    <Adress_pernam>
      <City>Wrocław</City>
      <Street>Borowska</Street>
    </Adress_pernam>
    <Adress_temp>
      <City>Kraków</City>
      <Street>Lotnicza</Street>
    </Adress_temp>
    <Classes>
      <Class>
        <Name>Logika</Name>
        <Grade>5</Grade>
      </Class>
    </Classes>
  </Student>
</Students>
